### ISSUE TITLE
No wget on a mac...

### ISSUE THREAD

**Issue by andreww** [lexnederbragt/swc-instructor-retreat-2015-3PM-UTC#1]
by default. `curl -O` instead.

**Comment by dpshelio** [comment]
archlinux and other linux distribution don't ship wget by default either. `curl -O <link>` works there too.

**Comment by andreww** [comment]
Only it doesn't work with the redirects used by Dropbox - you just get some html.

**Comment by andreww** [comment]
So you can use the link provided...

**Comment by lexnederbragt** [comment]
Solution:  `Curl -O`
