### ISSUE TITLE
Can't compile on Debian8

### ISSUE THREAD

**Issue by anthonyharrison** [lexnederbragt/swc-instructor-retreat-2015-3PM-UTC#2]
Can't find sys/cdefs.h

Think it is very clear that the set of pre-requisites for the exercise need to be very clearly stated beforehand. If not you spend all your time fixing problems and not listening to the lesson.

**Comment by jcamins** [comment]
I believe the headers are provided by libc6-dev (or something like that).

**Comment by jcamins** [comment]
Confirmed, `apt-get install libc6-dev` should install the headers for your particular architecture.

**Comment by jcamins** [comment]
Per @anthonyharrison, you can also just install using apt-get: `apt-get install velvet`

**Comment by lexnederbragt** [comment]
Solution: `apt-get install velvet`
